repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.3.0
  hooks:
    - id: mypy
      args: [--ignore-missing-imports]
      exclude: ".*_pb2\\.py$"
      additional_dependencies: ['types-protobuf']

- repo: local
  hooks:
    - id: prettier
      name: Prettier
      entry: bash -c 'cd app && npx prettier --write $(echo "$@" | sed "s|app/||g")' --
      language: node
      types_or: [svelte, javascript, ts, json, css, markdown]
      additional_dependencies: ['prettier@3.0.3', 'prettier-plugin-svelte@3.0.0']
      files: ^app/
