repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black

- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: mypy
      language: python
      types: [python]
      args: [
        "--config-file=server/bridge/pyproject.toml",
        "--ignore-missing-imports",
        "--follow-imports=silent",
      ]
      exclude: ".*_pb2\\.py$"
      additional_dependencies: ['mypy>=1.8.0', 'mypy-protobuf>=3.6.0', 'types-protobuf>=5.29.1']
    - id: prettier
      name: Prettier
      entry: bash -c 'cd app && npx prettier --write $(echo "$@" | sed "s|app/||g")' --
      language: node
      types_or: [svelte, javascript, ts, json, css, markdown]
      additional_dependencies: ['prettier@3.0.3', 'prettier-plugin-svelte@3.0.0']
      files: ^app/
