[package]
name = "portico-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.12.0", features = ["v4"] }
anyhow = "1.0.95"
reqwest = { version = "0.12.12", features = ["json"] }
chrono = { version = "0.4", features = ["serde"] }
cron = "0.15.0"
async-trait = "0.1.85"
glob = "0.3.2"
postgrest = "1.6.0"
rand = "0.8"
pyo3 = { version = "0.23.4", features = ["auto-initialize"] }
openssl = "0.10.71"
sqlx = { version = "0.8.3", features = ["postgres"] }
dotenvy = "0.15.7"
