services:
  # Use Supabase CLI to start all Supabase services based on config.toml
  supabase:
    image: supabase/cli:latest
    volumes:
      - ./supabase:/supabase
    ports:
      - "54321:54321" # API
      - "54322:54322" # DB
      - "54323:54323" # Studio
      - "54324:54324" # Inbucket
      - "54327:54327" # Analytics
    command: start
    networks:
      - portico-network

  # Bridge service connects to Supabase and forwards signals to the engine
  bridge:
    build: ./bridge
    depends_on:
      - engine
    networks:
      - portico-network
    restart: unless-stopped

  # Engine service processes signals from the bridge
  engine:
    build: ./engine
    depends_on:
      - supabase
    ports:
      - "8888:8888"
    networks:
      - portico-network
    restart: unless-stopped

networks:
  portico-network:
    driver: bridge

volumes:
  postgres_data:
