services:
  # NOTE: Expect supabase to be running locally (with `supabase start`)
  # Bridge service connects to Supabase and forwards signals to the engine
  bridge:
    build:
      context: ..
      dockerfile: ./server/bridge/Dockerfile
    # No volumes needed as files are copied in the Dockerfile
    depends_on:
      - engine
    networks:
      - portico-network
    restart: unless-stopped
    env_file:
      - ./bridge/.env

  # Engine service processes signals from the bridge
  engine:
    build:
      context: ..
      dockerfile: ./server/engine/Dockerfile
    ports:
      - "50051:50051"
    networks:
      - portico-network
    restart: unless-stopped
    env_file:
      - ./engine/.env

networks:
  portico-network:
    driver: bridge

volumes:
  postgres_data:
