# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bridge_message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "bridge_message.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14\x62ridge_message.proto\x12\x07portico\x1a\x1cgoogle/protobuf/struct.proto"(\n\x11ServerInitRequest\x12\x13\n\x0bserver_init\x18\x01 \x01(\x08"6\n\x12ServerInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t"T\n\x0cSupabaseData\x12\r\n\x05table\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\'\n\x06record\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct"\xbc\x01\n\x06Signal\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x13\n\x0bsignal_type\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12/\n\x08metadata\x18\x06 \x03(\x0b\x32\x1d.portico.Signal.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"\xb7\x01\n\tAgentData\x12\x13\n\x0bglobal_uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12<\n\rconfiguration\x18\x04 \x03(\x0b\x32%.portico.AgentData.ConfigurationEntry\x1a\x34\n\x12\x43onfigurationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"4\n\rSignalRequest\x12#\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x15.portico.SupabaseData"3\n\x0c\x41gentRequest\x12#\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x15.portico.SupabaseData"5\n\x11OperationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xe0\x02\n\rBridgeService\x12\x45\n\nInitServer\x12\x1a.portico.ServerInitRequest\x1a\x1b.portico.ServerInitResponse\x12\x42\n\x0c\x43reateSignal\x12\x16.portico.SignalRequest\x1a\x1a.portico.OperationResponse\x12@\n\x0b\x43reateAgent\x12\x15.portico.AgentRequest\x1a\x1a.portico.OperationResponse\x12@\n\x0bUpdateAgent\x12\x15.portico.AgentRequest\x1a\x1a.portico.OperationResponse\x12@\n\x0b\x44\x65leteAgent\x12\x15.portico.AgentRequest\x1a\x1a.portico.OperationResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "bridge_message_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SIGNAL_METADATAENTRY"]._loaded_options = None
    _globals["_SIGNAL_METADATAENTRY"]._serialized_options = b"8\001"
    _globals["_AGENTDATA_CONFIGURATIONENTRY"]._loaded_options = None
    _globals["_AGENTDATA_CONFIGURATIONENTRY"]._serialized_options = b"8\001"
    _globals["_SERVERINITREQUEST"]._serialized_start = 63
    _globals["_SERVERINITREQUEST"]._serialized_end = 103
    _globals["_SERVERINITRESPONSE"]._serialized_start = 105
    _globals["_SERVERINITRESPONSE"]._serialized_end = 159
    _globals["_SUPABASEDATA"]._serialized_start = 161
    _globals["_SUPABASEDATA"]._serialized_end = 245
    _globals["_SIGNAL"]._serialized_start = 248
    _globals["_SIGNAL"]._serialized_end = 436
    _globals["_SIGNAL_METADATAENTRY"]._serialized_start = 389
    _globals["_SIGNAL_METADATAENTRY"]._serialized_end = 436
    _globals["_AGENTDATA"]._serialized_start = 439
    _globals["_AGENTDATA"]._serialized_end = 622
    _globals["_AGENTDATA_CONFIGURATIONENTRY"]._serialized_start = 570
    _globals["_AGENTDATA_CONFIGURATIONENTRY"]._serialized_end = 622
    _globals["_SIGNALREQUEST"]._serialized_start = 624
    _globals["_SIGNALREQUEST"]._serialized_end = 676
    _globals["_AGENTREQUEST"]._serialized_start = 678
    _globals["_AGENTREQUEST"]._serialized_end = 729
    _globals["_OPERATIONRESPONSE"]._serialized_start = 731
    _globals["_OPERATIONRESPONSE"]._serialized_end = 784
    _globals["_BRIDGESERVICE"]._serialized_start = 787
    _globals["_BRIDGESERVICE"]._serialized_end = 1139
# @@protoc_insertion_point(module_scope)
