# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bridge_message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "bridge_message.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14\x62ridge_message.proto\x12\x07portico\x1a\x1cgoogle/protobuf/struct.proto"(\n\x11ServerInitRequest\x12\x13\n\x0bserver_init\x18\x01 \x01(\x08"3\n\x0fGeneralResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t"\xec\x01\n\rSignalRequest\x12\x13\n\x0bsignal_uuid\x18\x01 \x01(\t\x12\x12\n\nagent_uuid\x18\x02 \x01(\t\x12(\n\x0bsignal_type\x18\x03 \x01(\x0e\x32\x13.portico.SignalType\x12*\n\x07\x63ommand\x18\x04 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x12$\n\x04sync\x18\x05 \x01(\x0b\x32\x14.portico.SyncPayloadH\x00\x12+\n\x08\x66yi_data\x18\x06 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x42\t\n\x07payload"~\n\x0eSignalResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1c\n\x14runtime_session_uuid\x18\x03 \x01(\t\x12,\n\x0bresult_data\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct"A\n\x12\x43reateAgentRequest\x12+\n\nagent_json\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct"(\n\x12\x44\x65leteAgentRequest\x12\x12\n\nagent_uuid\x18\x01 \x01(\t"E\n\x0bSyncPayload\x12!\n\x05scope\x18\x01 \x01(\x0e\x32\x12.portico.SyncScope\x12\x13\n\x0b\x61gent_uuids\x18\x02 \x03(\t*(\n\nSignalType\x12\x07\n\x03RUN\x10\x00\x12\x08\n\x04SYNC\x10\x01\x12\x07\n\x03\x46YI\x10\x02*"\n\tSyncScope\x12\x07\n\x03\x41LL\x10\x00\x12\x0c\n\x08SPECIFIC\x10\x01\x32\xa1\x02\n\rBridgeService\x12\x42\n\nInitServer\x12\x1a.portico.ServerInitRequest\x1a\x18.portico.GeneralResponse\x12@\n\rProcessSignal\x12\x16.portico.SignalRequest\x1a\x17.portico.SignalResponse\x12\x44\n\x0b\x43reateAgent\x12\x1b.portico.CreateAgentRequest\x1a\x18.portico.GeneralResponse\x12\x44\n\x0b\x44\x65leteAgent\x12\x1b.portico.DeleteAgentRequest\x1a\x18.portico.GeneralResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "bridge_message_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SIGNALTYPE"]._serialized_start = 705
    _globals["_SIGNALTYPE"]._serialized_end = 745
    _globals["_SYNCSCOPE"]._serialized_start = 747
    _globals["_SYNCSCOPE"]._serialized_end = 781
    _globals["_SERVERINITREQUEST"]._serialized_start = 63
    _globals["_SERVERINITREQUEST"]._serialized_end = 103
    _globals["_GENERALRESPONSE"]._serialized_start = 105
    _globals["_GENERALRESPONSE"]._serialized_end = 156
    _globals["_SIGNALREQUEST"]._serialized_start = 159
    _globals["_SIGNALREQUEST"]._serialized_end = 395
    _globals["_SIGNALRESPONSE"]._serialized_start = 397
    _globals["_SIGNALRESPONSE"]._serialized_end = 523
    _globals["_CREATEAGENTREQUEST"]._serialized_start = 525
    _globals["_CREATEAGENTREQUEST"]._serialized_end = 590
    _globals["_DELETEAGENTREQUEST"]._serialized_start = 592
    _globals["_DELETEAGENTREQUEST"]._serialized_end = 632
    _globals["_SYNCPAYLOAD"]._serialized_start = 634
    _globals["_SYNCPAYLOAD"]._serialized_end = 703
    _globals["_BRIDGESERVICE"]._serialized_start = 784
    _globals["_BRIDGESERVICE"]._serialized_end = 1073
# @@protoc_insertion_point(module_scope)
