[package]
name = "portico-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
portico-shared = { path = "../../shared" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
